#!/bin/bash

# Test if a listing has a single file in its "root":
#
#   - Listings with one file are always considered single-root
#   - Listings with multiple files in a shared subdirectory are single-root:
#        * Foo/1
#        * Foo/2
#        * Foo/...
#   - Listings with absolute paths with more than one file are NOT single-root
#   - Anything else is also not single-root

export IFS="/"
lc=0
while read -ra line ; do
    # Handle absolute paths
    if [ $lc -gt 0 -a -z "${line[0]}" ]; then
        exit 1
    fi

    # Otherwise anytime this root is different than the last, we've found
    # multi-root
    if [ $lc -gt 0 -a "${line[0]}" != "$last" ]; then
        exit 1
    fi
    last="${line[0]}"
    let lc++
done

exit 0
