#!/bin/bash

archive=$1
cmd=$2

case "$cmd" in
    decompress) bunzip2 $archive ;;
    compress) bzip2 -9 $archive ;;
    cat) bzcat $archive ;;
    basename) basename "$archive" .bz2 ;;
    *) $amlib/error "$0: Unknown command: $cmd" ; exit 1 ;;
esac
