#!/bin/bash

cmd=$1
archive=$2

case "$cmd" in
    decompress) gunzip $archive ;;
    compress) gzip -9 $archive ;;
    cat) zcat $archive ;;
    basename) basename "$archive" .gz ;;
    *) $amlib/error "$0: Unknown command: $cmd" ; exit 1 ;;
esac
