#!/bin/bash

archive=$1
cmd=$2

case "$cmd" in
    decompress) gunzip $archive ;;
    compress) gzip -9 $archive ;;
    cat) zcat $archive ;;
    basename)
        if [[ "$archive" =~ \.tgz$ ]]; then
            echo $(basename "$archive" .tgz).tar
        else
            basename "$archive" .gz
        fi
        ;;
    *) $amlib/error "$0: Unknown command: $cmd" ; exit 1 ;;
esac
