#!/bin/bash

while [ "$1" ]; do
    opt="$1"
    case "$opt" in
        -c|--create) create=1;;
        *) break;
    esac
    shift
done

archive=$1
shift

if [ -z "$archive" ]; then
    $amlib/error "$0: no archive specified"
    exit 1
fi

if $am list $archive | $amlib/is-list-single-root; then
    echo .
    exit 0
fi

target=$($am basename $archive)

if [ "$create" ]; then
    if [ -e "$target" ]; then
        oldtarget=$target
        target=$(mktemp -d $target-XXXXXXXXXX)
    else
        mkdir $target
    fi
fi

echo $target
