#!/bin/bash

usage() {
    echo "am extraction-target ARCHIVE"
    echo
    echo "Create a temporary directory in which to extract ARCHIVE."
}

archive=$1
shift

if [ -z "$archive" ]; then
    $amlib/error "$0: no archive specified"
    exit 1
fi

basename=$($am $archive basename)
target=$(mktemp -d $basename-XXXXX)

echo $target
