#!/bin/bash

## Keep lines sorted

declare -A mime_suite=(
    ["application/x-cpio"]="cpio"
    ["application/x-rar"]="rar"
    ["application/x-tar"]="tar"
    ["application/zip"]="zip"
    ["application/x-7z-compressed"]="7z"
)

declare -A mime_comp=(
    ["application/gzip"]="gzip"
    ["application/x-bzip2"]="bzip2"
    ["application/x-compress"]="compress"
    ["application/x-gzip"]="gzip"
    ["application/x-xz"]="xz"
)

declare -A ext_suite=(
    ["cpio"]="cpio"
    ["rar"]="rar"
    ["tar"]="tar"
    ["zip"]="zip"
    ["7z"]="7z"
)

declare -A ext_comp=(
    ["Z"]="compress"
    ["bz2"]="bzip2"
    ["gz"]="gzip"
    ["xz"]="xz"
    ["z"]="compress"
)

##

archive="$1"

type_from_existing() {
    mime_type=$(file -b --mime-type "$archive")

    suite=${mime_suite[$mime_type]}
    comp=${mime_comp[$mime_type]}

    if [ -z "$comp" -a -z "$suite" ]; then
        file_type=$(file "$archive")

        $amlib/error "Unknown archive type: $mime_type ($file_type)"
        exit 1
    fi

    if [ -z "$suite" ]; then
        comp_tool=$amlib/comp-$comp

        nested_mime=$($comp_tool "$archive" cat | file -b --mime-type -)
        suite=${mime_suite[$nested_mime]}
    fi

    if [ "$comp" ]; then
        echo "$amlib/suite-$suite --comp $comp_tool"
    else
        echo "$amlib/suite-$suite"
    fi
}

type_from_extension() {
    # this is terrible and ought to be fixed

    IFS="."
    read -ra tool <<< "$archive"
    last=$(( ${#tool[@]} - 1 ))
    let next=last-1

    suite=${ext_suite[${tool[$last]}]}
    comp=${ext_comp[${tool[$last]}]}

    if [ -z "$suite" -a -z "$comp" ]; then
        $amlib/error "Unable to determine suite or compression from filename: '$archive'"
        exit 1;
    fi

    if [ -z "$suite" ]; then
        suite=${ext_suite[${tool[$next]}]}
        if [ -z "$suite" ]; then
            $amlib/error "Unknown suite for filename: '$archive'"
        fi
    fi

    if [ "$comp" ]; then
        comp_tool=$amlib/comp-$comp
        echo "$amlib/suite-$suite --comp $comp_tool"
    else
        echo "$amlib/suite-$suite"
    fi
}

if [ -e "$archive" ]; then
    type_from_existing
else
    type_from_extension
fi
