#!/bin/bash

declare -A mime_suite=(
    ["application/x-rar"]="rar"
    ["application/x-tar"]="tar"
    ["application/zip"]="zip"
)

declare -A mime_comp=(
    ["application/gzip"]="gzip"
)

archive="$1"
mime_type=$(file -b --mime-type $archive)

suite=${mime_suite[$mime_type]}
comp=${mime_comp[$mime_type]}

if [ -z "$comp" -a -z "$suite" ]; then
    file_type=$(file $archive)

    $amlib/error "Unknown archive type: $mime_type ($file_type)"
    exit 1
fi

if [ -z "$suite" ]; then
    comp_tool=$amlib/comp-$comp

    nested_mime=$($comp_tool cat $archive | file -b --mime-type -)
    suite=${mime_suite[$nested_mime]}
fi

if [ "$comp" ]; then
    echo "$amlib/suite-$suite --comp $comp_tool"
else
    echo "$amlib/suite-$suite"
fi
