#!/bin/bash

comp_default=$amlib/comp-cat

usage() {
    echo
    echo "am/suite-tar [OPTIONS...] <archive> c FILES..."
    echo "am/suite-tar [OPTIONS...] <archive> <l|x>"
    echo
    echo "    basename               Basename of a foo.zip file (e.g., foo)"
    echo "    c, create              Create archive from files"
    echo "    l, list                List files in archive"
    echo "    x, extract             Extract files in archive"
    echo
    echo "Options:"
    echo "    --comp TOOL            Compression tool for pre/post process"
    echo "    -h, --help             This help"
    echo
}

while [ "$1" ]; do
    opt="$1"
    case "$opt" in
        --comp) shift; comp_tool="$1" ;;
        -h|--help) usage ; exit ;;
        *) break ;;
    esac
    shift
done

archive=$(realpath "$1"); shift
cmd="$1"; shift

if [ -z "$cmd" ]; then
    cmd='help'
fi

if [ -z "$comp_tool" ]; then
    comp_tool="$comp_default"
fi

case "$cmd" in
    basename)
        echo $(basename $($comp_tool "$archive" basename) .tar)
        ;;
    c|create)
        if [ -e "$archive" ]; then
            $amlib/error "Not creating archive over existing file: "$archive""
            exit 1;
        fi

        tar cvf - -- "$@" | $comp_tool - compress > "$archive"
        ;;

    h|help) usage; exit 0;;

    l|list)
        ($comp_tool "$archive" cat) | tar tvf - |
            while read -ra line; do
                echo "${line[5]}"
            done
        ;;
    x|extract)
        target=$($amlib/extraction-target "$archive")
        cwd=$PWD
        cd "$target"
        ($comp_tool "$archive" cat) | tar xvf -
        cd $cwd

        $amlib/temp-dir-cleanup "$target"
        ;;

    *) $amlib/error "Unknown command: $cmd"; usage; exit 1 ;;
esac
