#!/bin/bash

comp_default=am-cat

usage() {
    echo
    echo "am/suite-tar [OPTIONS...] <cmd> <archive>"
    echo
    echo "    l, list                list files in archive"
    echo
    echo "Options:"
    echo "    --comp TOOL            Compression tool for pre/post process"
    echo "    -h, --help             This help"
    echo
}

while [ "$1" ]; do
    opt="$1"
    case "$opt" in
        --comp) shift; comp="$1" ;;
        -h|--help) usage ; exit ;;
        *) break ;;
    esac
    shift
done

cmd="$1"
archive=$(realpath $2)
shift 2

case "$cmd" in
    basename)
        echo $(basename $($comp basename $archive) .tar)
        ;;
    c|create)
        if [ -e "$archive" ]; then
            $amlib/error "Not creating archive over existing file: $archive"
            exit 1;
        fi

        tar cvf - -- "$@" | $comp compress - > $archive
        ;;
    l|list)
        ($comp cat $archive) | tar tvf - |
            while read -ra line; do
                echo "${line[5]}"
            done
        ;;
    x|extract)
        target=$($amlib/extraction-target -c $archive)
        cd $target
        ($comp cat $archive) | tar xvf -

        echo
        echo Extracted to $target/
        ;;
esac
