#!/bin/bash

usage() {
    echo
    echo "am/suite-zip [OPTIONS...] <archive> c FILES..."
    echo "am/suite-zip [OPTIONS...] <archive> <l|x>"
    echo
    echo "    basename               Basename of a foo.zip file (e.g., foo)"
    echo "    c, create              Create an archive"
    echo "    l, list                List files in archive"
    echo "    x, extract             Extract archive"
    echo
    echo "Options:"
    echo "    -h, --help             This help"
    echo
}

while [ "$1" ]; do
    case "$opt" in
        -h|--help) usage ; exit ;;
        *) break ;;
    esac
    shift
done

archive=$(realpath "$1"); shift
cmd="$1"; shift

if [ -z "$cmd" ]; then
    usage
    exit
fi

case "$cmd" in
    basename)
        echo $(basename "$archive" .zip)
        ;;
    c|create)
        if [ -e "$archive" ]; then
            $amlib/error "Not creating archive over existing file: "$archive""
            exit 1;
        fi

        zip -r "$archive" -- "$@"
        ;;
    l|list)
        first=
        unzip -l "$archive" |
            while read -ra line; do
                linechar="${line[0]:0:1}"
                if [ "$first" ]; then
                    [ "$linechar" == "-" ] && break
                    echo "${line[3]}"
                elif [ "$linechar" == "-" ]; then
                    first=1
                fi
            done
        ;;
    x|extract)
        target=$($amlib/extraction-target "$archive")
        cwd=$PWD
        cd "$target"
        unzip "$archive"
        cd $cwd

        $amlib/temp-dir-cleanup "$target"
        ;;
esac
