#!/bin/bash

comp_default=am-cat

usage() {
    echo
    echo "am/suite-tar [OPTIONS...] <archive> c FILES..."
    echo "am/suite-tar [OPTIONS...] <archive> <l|x>"
    echo
    echo "    basename               Basename of a foo.zip file (e.g., foo)"
    echo "    c, create              Create archive from files"
    echo "    l, list                List files in archive"
    echo "    x, extract             Extract files in archive"
    echo
    echo "Options:"
    echo "    --comp TOOL            Compression tool for pre/post process"
    echo "    -h, --help             This help"
    echo
}

while [ "$1" ]; do
    opt="$1"
    case "$opt" in
        --comp) shift; comp="$1" ;;
        -h|--help) usage ; exit ;;
        *) break ;;
    esac
    shift
done

archive=$(realpath $1)
cmd="$2"
shift 2

if [ -z "$cmd" ]; then
    cmd='help'
fi

case "$cmd" in
    basename)
        echo $(basename $($comp basename $archive) .tar)
        ;;
    c|create)
        if [ -e "$archive" ]; then
            $amlib/error "Not creating archive over existing file: $archive"
            exit 1;
        fi

        tar cvf - -- "$@" | $comp compress - > $archive
        ;;

    h|help) usage; exit 0;;

    l|list)
        ($comp cat $archive) | tar tvf - |
            while read -ra line; do
                echo "${line[5]}"
            done
        ;;
    x|extract)
        target=$($amlib/extraction-target -c $archive)
        cd $target
        ($comp cat $archive) | tar xvf -

        echo
        echo Extracted to $target/
        ;;

    *) $amlib/error "Unknown command: $cmd"; usage; exit 1 ;;
esac
