#!/bin/bash

usage() {
    echo
    echo "am/suite-tar [OPTIONS...] <cmd> <archive>"
    echo "    basename               Basename of a foo.zip file (e.g., foo)"
    echo "    c, create              Create an archive"
    echo "    l, list                List files in archive"
    echo "    x, extract             Extract archive"
    echo
    echo "Options:"
    echo "    -h, --help             This help"
    echo
}

while [ "$1" ]; do
    opt="$1"
    case "$opt" in
        -h|--help) usage ; exit ;;
        *) break ;;
    esac
    shift
done

cmd="$1"
archive=$(realpath -e $2)
shift 2

case "$cmd" in
    basename)
        echo $(basename "$archive" .zip)
        ;;
    c|create)
        if [ -e "$archive" ]; then
            $amlib/error "Not creating archive over existing file: $archive"
            exit 1;
        fi

        zip $archive -- "$@"
        ;;
    l|list)
        lc=0
        unzip -l $archive |
            while read -ra line; do
                if [ $lc -gt 2 ]; then
                    if [ "${line[0]:0:1}" == "-" ]; then
                        break;
                    fi

                    echo "${line[3]}"
                fi
                let lc++
            done
        ;;
    x|extract)
        target=$($amlib/extraction-target -c $archive)
        cd $target
        unzip $archive

        echo
        echo Extracted to $target/
        ;;
esac
