#!/bin/bash

usage() {
    echo
    echo "am/suite-rar [OPTIONS...] <cmd> <archive>"
    echo
    echo "    basename               Basename of a foo.zip file (e.g., foo)"
    echo "    l, list                List files in archive"
    echo "    x, extract             Extract archive"
    echo
    echo "Options:"
    echo "    -h, --help             This help"
    echo
    echo "Note: rar doesn't support archive creation at this time."
}

while [ "$1" ]; do
    opt="$1"
    case "$opt" in
        -h|--help) usage ; exit ;;
        *) break ;;
    esac
    shift
done

archive=$(realpath $1)
cmd="$2"
shift 2

case "$cmd" in
    basename)
        echo $(basename "$archive" .rar)
        ;;
    c|create)
        echo "Creating RAR is unsupported at this time"
        exit 1
        ;;
    l|list)
        unrar v $archive |
            while read -ra line; do
                if [ "$past_head" ]; then
                    if [ "${line[0]:0:1}" == "-" ]; then
                        break;
                    fi

                    echo "${line[7]}"
                elif [ "${line[0]:0:1}" == "-" ]; then
                    past_head=1
                fi
            done
        ;;
    x|extract)
        target=$($amlib/extraction-target $archive)
        cwd=$PWD
        cd $target
        unrar x -y $archive
        cd $cwd

        $amlib/temp-dir-cleanup $target
        ;;
esac
